import { motion } from 'framer-motion';
import { useNavigate } from 'react-router-dom';
import { Sparkles, ArrowRight, Zap, Eye, Brain, Lock, Crown, Mic, Home, Video, GitBranch, Timer, MessageSquareText, Coins, Wand2 } from 'lucide-react';

function Landing() {
  const navigate = useNavigate();

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      transition={{ duration: 0.8 }}
      className="min-h-screen relative overflow-hidden grid-bg"
    >
      {/* Background orbs */}
      <div className="absolute inset-0 pointer-events-none">
        <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-neon-blue/10 rounded-full blur-[120px] animate-pulse-glow" />
        <div className="absolute bottom-1/4 right-1/4 w-80 h-80 bg-neon-cyan/10 rounded-full blur-[100px] animate-pulse-glow" style={{ animationDelay: '1.5s' }} />
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] bg-neon-teal/5 rounded-full blur-[150px] animate-pulse-glow" style={{ animationDelay: '3s' }} />
      </div>

      {/* Decorative rotating ring */}
      <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 pointer-events-none">
        <div className="w-[700px] h-[700px] md:w-[900px] md:h-[900px] border border-neon-blue/5 rounded-full animate-rotate-slow" />
        <div className="absolute top-0 left-0 w-full h-full border border-neon-cyan/5 rounded-full animate-rotate-slow" style={{ animationDirection: 'reverse', animationDuration: '30s' }} />
      </div>

      {/* Content */}
      <div className="relative z-10 min-h-screen flex flex-col items-center justify-center px-6 py-12">
        {/* Top badge */}
        <motion.div
          initial={{ y: -20, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          transition={{ delay: 0.3, duration: 0.6 }}
          className="glass-card px-4 py-2 mb-8 flex items-center gap-2"
        >
          <Zap className="w-4 h-4 text-neon-cyan" />
          <span className="text-sm text-neon-cyan font-medium tracking-wide">Powered by AI</span>
        </motion.div>

        {/* Main title */}
        <motion.h1
          initial={{ y: 30, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          transition={{ delay: 0.5, duration: 0.8 }}
          className="font-orbitron text-4xl sm:text-5xl md:text-7xl font-bold text-center leading-tight mb-6"
        >
          <span className="text-white">See Your</span>
          <br />
          <span className="neon-text">Future Self</span>
        </motion.h1>

        {/* Subtitle */}
        <motion.p
          initial={{ y: 20, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          transition={{ delay: 0.8, duration: 0.6 }}
          className="text-gray-400 text-lg md:text-xl text-center max-w-xl mb-12 leading-relaxed"
        >
          Your future is generated by AI based on your current choices.
          Discover who you'll become in 15 years.
        </motion.p>

        {/* Feature cards */}
        <motion.div
          initial={{ y: 30, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          transition={{ delay: 1, duration: 0.6 }}
          className="flex flex-wrap justify-center gap-4 mb-12 max-w-2xl"
        >
          {[
            { icon: Brain, label: 'AI-Generated Story' },
            { icon: Eye, label: 'Future Timeline' },
            { icon: Sparkles, label: 'Personal Advice' },
          ].map((feature, i) => (
            <div
              key={i}
              className="glass-card px-5 py-3 flex items-center gap-2 hover:neon-border transition-all duration-300"
            >
              <feature.icon className="w-4 h-4 text-neon-blue" />
              <span className="text-sm text-gray-300">{feature.label}</span>
            </div>
          ))}
        </motion.div>

        {/* CTA button */}
        <motion.button
          initial={{ y: 20, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          transition={{ delay: 1.2, duration: 0.6 }}
          whileHover={{ scale: 1.05 }}
          whileTap={{ scale: 0.97 }}
          onClick={() => navigate('/input')}
          className="btn-futuristic flex items-center gap-3 text-lg font-orbitron tracking-wide"
        >
          Enter the Future
          <ArrowRight className="w-5 h-5" />
        </motion.button>

        {/* Future+ Premium teaser */}
        <motion.div
          initial={{ y: 30, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          transition={{ delay: 1.6, duration: 0.6 }}
          className="mt-20 max-w-2xl w-full"
        >
          <div className="flex items-center justify-center gap-3 mb-6">
            <Crown className="w-4 h-4 text-neon-blue/60" />
            <span className="font-orbitron text-xs tracking-[0.2em] text-neon-blue/60 uppercase">Future+ Premium</span>
            <span className="font-orbitron text-[9px] tracking-wider text-neon-cyan/40 bg-neon-cyan/5 px-2 py-0.5 rounded-full border border-neon-cyan/10 uppercase">Locked</span>
          </div>

          <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
            {[
              { icon: Mic, label: 'AI Voice' },
              { icon: Home, label: 'Future House' },
              { icon: Video, label: 'Avatar Video' },
              { icon: GitBranch, label: 'Alt Paths' },
              { icon: Timer, label: '2050 Sim' },
              { icon: MessageSquareText, label: 'Future Chat' },
              { icon: Coins, label: 'Wealth Journey' },
              { icon: Wand2, label: 'Transform' },
            ].map((item, i) => (
              <div
                key={i}
                className="glass-card p-3 flex items-center gap-2 opacity-40 hover:opacity-60 transition-all duration-300 cursor-default"
              >
                <Lock className="w-3 h-3 text-neon-blue/40 flex-shrink-0" />
                <item.icon className="w-4 h-4 text-gray-500 flex-shrink-0" />
                <span className="text-xs text-gray-500 truncate">{item.label}</span>
              </div>
            ))}
          </div>
          <p className="text-center text-gray-600 text-[11px] mt-4 font-medium">
            Premium features arriving soon. Start with your free future prediction above.
          </p>
        </motion.div>

        {/* Bottom floating particles */}
        <div className="absolute bottom-8 left-1/2 -translate-x-1/2 flex gap-2">
          {[0, 1, 2, 3, 4].map((i) => (
            <div
              key={i}
              className="w-1.5 h-1.5 bg-neon-blue/40 rounded-full animate-float"
              style={{ animationDelay: `${i * 0.8}s` }}
            />
          ))}
        </div>
      </div>
    </motion.div>
  );
}

export default Landing;
